# Generated by Django 2.1.2 on 2019-12-27 14:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, unique=True)),
                ('description', models.CharField(max_length=120)),
                ('post_primary_image', models.CharField(max_length=120)),
                ('created', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('updated', models.DateTimeField(null=True)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=120)),
                ('comment', models.CharField(max_length=120)),
                ('created', models.DateTimeField(default=datetime.datetime.utcnow)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, unique=True)),
                ('description', models.CharField(max_length=120)),
                ('product_primary_image', models.CharField(max_length=120)),
                ('product_secondary_images', models.CharField(max_length=120)),
                ('hero_product', models.BooleanField(default=False)),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=datetime.datetime.utcnow)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, unique=True)),
                ('description', models.CharField(help_text='service description', max_length=120)),
                ('service_primary_image', models.CharField(help_text='main image to show in layout UI', max_length=120)),
                ('service_secondary_images', models.CharField(help_text='optional images to show if needed', max_length=120)),
                ('hero_service', models.BooleanField(default=False, help_text='is it to be placed on top of the service page? default to false')),
                ('created', models.DateTimeField(default=datetime.datetime.utcnow)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=120)),
                ('lastname', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=120, unique=True)),
                ('created', models.DateTimeField(default=datetime.datetime.utcnow)),
            ],
        ),
    ]
