# Generated by Django 2.1.2 on 2020-01-05 10:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kukhura', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='secondary_images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(help_text='optional images to show if needed'), null=True, size=None),
        ),
    ]
