# Generated by Django 2.1.2 on 2019-12-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kukhura', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='post_primary_image',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_primary_image',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_secondary_images',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(help_text='service description'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_primary_image',
            field=models.TextField(help_text='main image to show in layout UI'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_secondary_images',
            field=models.TextField(help_text='optional images to show if needed'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='firstname',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastname',
            field=models.TextField(),
        ),
    ]
