# Generated by Django 2.1.2 on 2019-12-27 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kukhura', '0006_auto_20191227_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='blogpost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kukhura.BlogPost'),
        ),
    ]
