# Generated by Django 2.1.2 on 2019-12-28 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kukhura', '0008_auto_20191227_2242'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
