# Generated by Django 2.1.2 on 2019-12-29 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kukhura', '0009_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='hero_post',
            field=models.BooleanField(default=False),
        ),
    ]
